# kubernetes-config/about-me.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-me
  labels:
    app: about-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: about-me
  template:
    metadata:
      labels:
        app: about-me
    spec:
      containers:
      - name: about-me
        image: gcr.io/celestial-ridge-273419/about-me:latest
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: about-me
spec:
  selector:
    app: about-me
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: about-me
spec:
  tls:
    - hosts:
        - "nitin-kumar.com"
        - "*.nitin-kumar.com"
      secretName: nitin-kumar-com-tls
  rules:
    - host: www.nitin-kumar.com
      http:
        paths:
          - path: /
            backend:
              serviceName: about-me
              servicePort: 80
    - host: nitin-kumar.com
      http:
        paths:
          - path: /
            backend:
              serviceName: about-me
              servicePort: 80