steps:
    #step 1
    - name: 'gcr.io/cloud-builders/docker' 
      entrypoint: 'bash'
      args: [
       '-c', 
       'docker pull gcr.io/$PROJECT_ID/about-me:latest || exit 0'
      ]
    #step 2
    - name: gcr.io/cloud-builders/docker
      args: [
       'build', 
       '-t', 
       'gcr.io/$PROJECT_ID/about-me:$BRANCH_NAME-$COMMIT_SHA',
       '-t', 
       'gcr.io/$PROJECT_ID/about-me:latest',
       '.'
      ]
    #step 3
    - name: 'gcr.io/cloud-builders/kubectl'
      args: ['apply', '-f', 'about-me.yaml']
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=personal-cluster'
    #step 4
    - name: 'gcr.io/cloud-builders/kubectl'
      args: [
       'set', 
       'image', 
       'deployment', 
       'about-me', 
       'about-me=gcr.io/$PROJECT_ID/about-me:$BRANCH_NAME-$COMMIT_SHA'
      ]
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=personal-cluster'